// Generated by https://quicktype.io
import { defineProps } from 'vue'

import type { SupplyPoint } from "./supply-point.interface";

export interface Client {
  full_name:     string;
  address:       string;
  cups:          string;
  role:          Role;
  building_type: Building;
}

export interface FullClientInfo extends Client, SupplyPoint {}

export enum Role { 
  Premium = "customer-premium", 
  Basic = "customer-basic", 
  Customer = "customer"
}

export enum Building {
  Apartment = "apartment",
  House = "house"
}